version: "3.7"

services:
  mautic:
    image: mautic/mautic:v4
    entrypoint: /entrypoint.sh
    command: apache2-foreground
    volumes:
      - mautic_data:/var/www/html
    networks:
      - minha_rede
    environment:
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysql_password
      - MAUTIC_ADMIN_EMAIL=jrafael5758@gmail.com
      - MAUTIC_ADMIN_PASSWORD=AdminPassword
      - MAUTIC_ADMIN_USERNAME=mautic
      - MAUTIC_URL=https://mautic.joserafael.dev.br
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.mautic.rule=Host(`mautic.joserafael.dev.br`)
        - traefik.http.routers.mautic.entrypoints=websecure
        - traefik.http.routers.mautic.tls.certresolver=letsencryptresolver
        - traefik.http.routers.mautic.service=mautic
        - traefik.http.services.mautic.loadbalancer.server.port=80
        - traefik.http.services.mautic.loadbalancer.passHostHeader=true

volumes:
  mautic_data:
    external: true
    name: mautic_data

networks:
  minha_rede:
    name: minha_rede
    external: true
