version: "3.7"

services:
  mysql:
    image: percona/percona-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - TZ=America/Brasilia
    networks:
      - minha_rede
    #ports:
    #  - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--sql-mode=",
        "--default-authentication-plugin=mysql_native_password",
        "--max-allowed-packet=512MB",
      ]

volumes:
  mysql_data:
    external: true
    name: mysql_data

networks:
  minha_rede:
    external: true
    name: minha_rede
