version: "3.7"

services:
  typebot_builder:
    image: baptistearno/typebot-builder:2.18.0
    networks:
      - minha_rede
    environment:
      - DATABASE_URL=postgresql://postgres:AdminAdmin@postgres:5432/typebot
      - ENCRYPTION_SECRET=7/l2NKGhkMUHRV0dt/g8hD2YNopCrAeH
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - NEXTAUTH_URL=https://typebot.joserafael.dev.br
      - NEXT_PUBLIC_VIEWER_URL=https://typebotapi.joserafael.dev.br
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - DISABLE_SIGNUP=false
      - ADMIN_EMAIL=jrafael5758@gmail.com
      - NEXT_PUBLIC_SMTP_FROM='Typebot' <jrafael5758@gmail.com>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=jrafael5758@gmail.com
      - SMTP_PASSWORD=xculnobalrjlkvnb
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=true
      # Configurações do Typebot e Google Cloud
      #- GOOGLE_CLIENT_ID=
      #- GOOGLE_CLIENT_SECRET=
      # Configurações do Typebot e Minio
      - S3_ACCESS_KEY=VMiTJxRB06RVhm1jjJqh
      - S3_SECRET_KEY=Zfuy8N6rudFdjDR90ux2QEiL3NvfgyPZ6XPRYPHY
      - S3_BUCKET=typebot
      - S3_ENDPOINT=apiminiobot.joserafael.dev.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.typebot_builder.rule=Host(`typebot.joserafael.dev.br`)
        - traefik.http.routers.typebot_builder.entrypoints=websecure
        - traefik.http.routers.typebot_builder.tls.certresolver=letsencryptresolver
        - traefik.http.services.typebot_builder.loadbalancer.server.port=3000
        - traefik.http.services.typebot_builder.loadbalancer.passHostHeader=true
        - traefik.http.routers.typebot_builder.service=typebot_builder
networks:
  minha_rede:
    external: true
    name: minha_rede
